name: 'Benchmark Record'
description: 'Build and publish Webots animation and save Benchmark score every 12 hours'
branding:
  icon: 'play'
  color: 'red'

runs:
  using: 'composite'
  steps:
    - name: Get default controller name
      run: ${{ github.action_path }}/default_controller_name_regex.sh
      shell: bash

    - name: Run the python meta script
      run: |
        cp -r ${{ github.action_path }}/metascript .
        python3 -u -m metascript
      shell: bash