name: 'Benchmark Record'
description: 'Build and publish Webots animation and save Benchmark score every 12 hours'
branding:
  icon: 'play'
  color: 'red'
inputs:
  push_token:
    description: 'Token needed to push animations to remote'
    required: true
    default: ${{ github.token }}

  fetch_token:
    description: 'Token needed to fetch competitors controllers'
    required: true
    default: ${{ github.token }}

  default_controller:
    description: 'Default name of the controller that will be used for the benchmark'
    required: true

  individual_evaluation:
    description: |
      "Indicates if an individual evaluation is requested, leave null if you want to evaluate everybody.
        the format is the same as the competitors.txt: id:username/repoName"
    required: true

  PROJECT_PATH:
    description: |
      "Project path used by webots.cloud simulation server"
    required: true


runs:
  using: 'composite'
  steps:
    - name: Run the python meta script
      run: |
        export PATH="$PATH:${{ github.action_path }}"
        ls -a ${{ github.action_path }}
        python3 -u benchmark_record_action -m
      shell: bash