name: 'Benchmark Record'
description: 'Build and publish Webots animation and save Benchmark score every 12 hours'
branding:
  icon: 'play'
  color: 'red'

runs:
  using: 'composite'
  steps:
    - name: Run the python meta script
      run: |
        cp -r ${{ github.action_path }}/metascript .
        ls
        python3 -u -m metascript
      shell: bash