name: 'Benchmark Record'
description: 'Build and publish Webots animation and save Benchmark score every 12 hours'
branding:
  icon: 'play'
  color: 'red'
inputs:
  push_token:
    description: 'Token needed to push animations to remote'
    required: false
    default: ${{ github.token }}
  pull_token:
    description: 'Token needed to fetch competitors controllers'
    required: false
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile'