name: 'Competition Record'
description: 'Build and publish Webots animation and save competition score'
branding:
  icon: 'play'
  color: 'red'

runs:
  using: 'composite'
  steps:
    - name: Run the python meta script
      run: |
        # cp -r ${{ github.action_path }}/metascript .
        # python3 -u -m metascript
        python3 -u ${{ github.action_path }}/metascript/__main__.py
      shell: bash
